spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce?serverTimezone=Australia/Melbourne&characterEncoding=utf-8
    username: root
    password: Ppr783305
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email,profile,openid
        provider:
          google:
           user-name-attribute: email



aws:
  s3:
    bucket: ${AWS_BUCKET_NAME}
  region: ${AWS_REGION}
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

